[template]
keys = [ 
 "/ntipa/apis/authserver", 
 "/ntipa/apis/box",
 "/ntipa/apis/manager"
]
owner = "root"
mode = "0644"
src = "nginx.conf.tmpl"
dest = "/etc/nginx/sites-enabled/app.conf"
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"