box:
  environment:
   - "MONGO_HOST=192.168.111.21"
   - "POSTGRES_HOST=192.168.111.21"
   - "SOLR_HOST=192.168.111.21"
   - "RABBITMQ_ADDRESSES=192.168.111.21:5672" 
  ports:
   - "8333:8333"
  expose:
   - "8333"     
  image: tornabene/ntipa-box
manager:
  ports:
   - "8081:8081"
  expose:
   - "8081"
  environment:
   - "MONGO_HOST=192.168.111.21"
   - "POSTGRES_HOST=192.168.111.21"
   - "SOLR_HOST=192.168.111.21"
   - "RABBITMQ_ADDRESSES=192.168.111.21:5672" 
  image: tornabene/ntipa-manager
#web:
#  dns:
#  - 10.10.130.35
#  - 8.8.8.8
#  ports:
#   - "80:80"
#  expose:
#   - "80"   
#  links:
#   - box
#   - manager
#   - manager:protocollo
#   - solr
#  image: tornabene/ntipa-nginx